package cmd

import (
	"camp/internal/project"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// setupEnvrcTemplate creates the .envrc template in the temp directory for testing
func setupEnvrcTemplate(t *testing.T, tmpDir string) {
	templateDir := filepath.Join(tmpDir, "templates", "files")
	if err := os.MkdirAll(templateDir, 0755); err != nil {
		t.Fatalf("Failed to create template directory: %v", err)
	}

	templateContent := `#!/bin/bash
# Generated by camp - DO NOT EDIT MANUALLY
# To update: modify .camp.yml and run 'camp project sync'

{{- if .HasDevbox }}

# Load devbox environment (if devbox.json exists)
if [ -f devbox.json ]; then
  eval "$(devbox generate direnv)"
fi
{{- end }}
{{- if .EnvVars }}

# Camp project environment variables
{{- range $key, $value := .EnvVars }}
export {{ $key }}="{{ escapeEnvValue $value }}"
{{- end }}
{{- end }}
`

	templatePath := filepath.Join(templateDir, ".envrc.tmpl")
	if err := os.WriteFile(templatePath, []byte(templateContent), 0644); err != nil {
		t.Fatalf("Failed to write template: %v", err)
	}
}

func TestInitCmd_CreatesConfigFile(t *testing.T) {
	// Create temporary directory
	tmpDir := t.TempDir()
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Run init command
	err := initProjectConfig()
	if err != nil {
		t.Fatalf("initProjectConfig() failed: %v", err)
	}

	// Verify .camp.yml was created
	configPath := filepath.Join(tmpDir, ".camp.yml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		t.Error("initProjectConfig() should create .camp.yml")
	}

	// Read and verify content
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("Failed to read .camp.yml: %v", err)
	}

	contentStr := string(content)

	// Check for expected sections
	if !strings.Contains(contentStr, "# Camp project configuration") {
		t.Error("Config should contain header comment")
	}

	if !strings.Contains(contentStr, "env:") {
		t.Error("Config should contain env section")
	}

	if !strings.Contains(contentStr, "PROJECT_NAME:") {
		t.Error("Config should contain PROJECT_NAME example")
	}

	if !strings.Contains(contentStr, "# Future: packages, flakes, scripts will go here") {
		t.Error("Config should contain future features comment")
	}
}

func TestInitCmd_FailsIfConfigExists(t *testing.T) {
	// Create temporary directory with existing .camp.yml
	tmpDir := t.TempDir()
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Create existing .camp.yml
	existingConfig := `env:
  EXISTING: "value"
`
	configPath := filepath.Join(tmpDir, ".camp.yml")
	if err := os.WriteFile(configPath, []byte(existingConfig), 0644); err != nil {
		t.Fatalf("Failed to create existing config: %v", err)
	}

	// Try to run init command
	err := initProjectConfig()
	if err == nil {
		t.Error("initProjectConfig() should fail when .camp.yml already exists")
	}

	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("Error message should mention 'already exists', got: %v", err)
	}
}

func TestInitCmd_FailsIfConfigExistsInParent(t *testing.T) {
	// Create temporary directory structure
	tmpDir := t.TempDir()
	subDir := filepath.Join(tmpDir, "subdir")
	if err := os.MkdirAll(subDir, 0755); err != nil {
		t.Fatalf("Failed to create subdirectory: %v", err)
	}

	// Create .camp.yml in parent
	parentConfig := `env:
  PARENT: "value"
`
	parentConfigPath := filepath.Join(tmpDir, ".camp.yml")
	if err := os.WriteFile(parentConfigPath, []byte(parentConfig), 0644); err != nil {
		t.Fatalf("Failed to create parent config: %v", err)
	}

	// Change to subdirectory
	oldWd, _ := os.Getwd()
	os.Chdir(subDir)
	defer os.Chdir(oldWd)

	// Try to run init command
	err := initProjectConfig()
	if err == nil {
		t.Error("initProjectConfig() should fail when .camp.yml exists in parent")
	}

	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("Error message should mention 'already exists', got: %v", err)
	}
}

func TestInitCmd_FilePermissions(t *testing.T) {
	// Create temporary directory
	tmpDir := t.TempDir()
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Run init command
	err := initProjectConfig()
	if err != nil {
		t.Fatalf("initProjectConfig() failed: %v", err)
	}

	// Check file permissions
	configPath := filepath.Join(tmpDir, ".camp.yml")
	info, err := os.Stat(configPath)
	if err != nil {
		t.Fatalf("Failed to stat .camp.yml: %v", err)
	}

	// Should be readable and writable by user
	mode := info.Mode()
	if mode.Perm()&0600 != 0600 {
		t.Errorf("Expected file to be readable and writable, got permissions: %o", mode.Perm())
	}
}

func TestInitCmd_ValidYAML(t *testing.T) {
	// Create temporary directory
	tmpDir := t.TempDir()
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Run init command
	err := initProjectConfig()
	if err != nil {
		t.Fatalf("initProjectConfig() failed: %v", err)
	}

	// Try to load the created config to verify it's valid YAML
	proj := project.NewProject(tmpDir)
	if !proj.HasCampConfig() {
		t.Error("Created config should be valid and loadable")
	}

	// Verify the template values
	envVars := proj.EnvVars()
	if envVars["PROJECT_NAME"] != "my-project" {
		t.Errorf("Expected PROJECT_NAME=my-project, got %s", envVars["PROJECT_NAME"])
	}
}

func TestSyncCmd_GeneratesEnvrc(t *testing.T) {
	// Create temporary directory
	tmpDir := t.TempDir()
	setupEnvrcTemplate(t, tmpDir)
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Create .camp.yml
	campYaml := `env:
  PROJECT_NAME: "test-project"
  DEBUG: "true"
  DATABASE_URL: "postgres://localhost/test"
`
	if err := os.WriteFile(".camp.yml", []byte(campYaml), 0644); err != nil {
		t.Fatalf("Failed to create .camp.yml: %v", err)
	}

	// Run sync command
	err := syncProjectEnv()
	if err != nil {
		t.Fatalf("syncProjectEnv() failed: %v", err)
	}

	// Verify .envrc was created
	envrcPath := filepath.Join(tmpDir, ".envrc")
	if _, err := os.Stat(envrcPath); os.IsNotExist(err) {
		t.Error("syncProjectEnv() should create .envrc")
	}

	// Read and verify content
	content, err := os.ReadFile(envrcPath)
	if err != nil {
		t.Fatalf("Failed to read .envrc: %v", err)
	}

	contentStr := string(content)

	// Check for expected exports
	if !strings.Contains(contentStr, "export PROJECT_NAME=\"test-project\"") {
		t.Error(".envrc should export PROJECT_NAME")
	}

	if !strings.Contains(contentStr, "export DEBUG=\"true\"") {
		t.Error(".envrc should export DEBUG")
	}

	if !strings.Contains(contentStr, "export DATABASE_URL=\"postgres://localhost/test\"") {
		t.Error(".envrc should export DATABASE_URL")
	}

	// Check for camp header
	if !strings.Contains(contentStr, "Generated by camp") {
		t.Error(".envrc should contain camp header")
	}
}

func TestSyncCmd_FailsWithoutCampConfig(t *testing.T) {
	// Create temporary directory without .camp.yml
	tmpDir := t.TempDir()
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Try to run sync command
	err := syncProjectEnv()
	if err == nil {
		t.Error("syncProjectEnv() should fail when .camp.yml doesn't exist")
	}

	if !strings.Contains(err.Error(), "not found") {
		t.Errorf("Error message should mention 'not found', got: %v", err)
	}
}

func TestSyncCmd_FindsConfigInParent(t *testing.T) {
	// Create temporary directory structure
	tmpDir := t.TempDir()
	subDir := filepath.Join(tmpDir, "subdir")
	if err := os.MkdirAll(subDir, 0755); err != nil {
		t.Fatalf("Failed to create subdirectory: %v", err)
	}

	// Setup template in subdirectory (where we'll run the command)
	setupEnvrcTemplate(t, subDir)

	// Create .camp.yml in parent
	parentYaml := `env:
  PARENT_VAR: "from-parent"
`
	parentConfigPath := filepath.Join(tmpDir, ".camp.yml")
	if err := os.WriteFile(parentConfigPath, []byte(parentYaml), 0644); err != nil {
		t.Fatalf("Failed to create parent config: %v", err)
	}

	// Change to subdirectory
	oldWd, _ := os.Getwd()
	os.Chdir(subDir)
	defer os.Chdir(oldWd)

	// Run sync command
	err := syncProjectEnv()
	if err != nil {
		t.Fatalf("syncProjectEnv() should find config in parent: %v", err)
	}

	// Verify .envrc was created in current dir (subdir)
	envrcPath := filepath.Join(subDir, ".envrc")
	if _, err := os.Stat(envrcPath); os.IsNotExist(err) {
		t.Error("syncProjectEnv() should create .envrc in current directory")
	}

	// Read and verify content
	content, err := os.ReadFile(envrcPath)
	if err != nil {
		t.Fatalf("Failed to read .envrc: %v", err)
	}

	contentStr := string(content)
	if !strings.Contains(contentStr, "export PARENT_VAR=\"from-parent\"") {
		t.Error(".envrc should export PARENT_VAR from parent config")
	}
}

func TestSyncCmd_OverwritesExistingEnvrc(t *testing.T) {
	// Create temporary directory
	tmpDir := t.TempDir()
	setupEnvrcTemplate(t, tmpDir)
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Create .camp.yml
	campYaml := `env:
  NEW_VAR: "new-value"
`
	if err := os.WriteFile(".camp.yml", []byte(campYaml), 0644); err != nil {
		t.Fatalf("Failed to create .camp.yml: %v", err)
	}

	// Create existing .envrc with old content
	oldEnvrc := `# Old content
export OLD_VAR="old-value"
`
	if err := os.WriteFile(".envrc", []byte(oldEnvrc), 0644); err != nil {
		t.Fatalf("Failed to create old .envrc: %v", err)
	}

	// Run sync command
	err := syncProjectEnv()
	if err != nil {
		t.Fatalf("syncProjectEnv() failed: %v", err)
	}

	// Read and verify new content
	content, err := os.ReadFile(".envrc")
	if err != nil {
		t.Fatalf("Failed to read .envrc: %v", err)
	}

	contentStr := string(content)

	// Should have new variable
	if !strings.Contains(contentStr, "export NEW_VAR=\"new-value\"") {
		t.Error(".envrc should contain NEW_VAR")
	}

	// Should NOT have old variable
	if strings.Contains(contentStr, "OLD_VAR") {
		t.Error(".envrc should not contain OLD_VAR (should be overwritten)")
	}

	// Should have camp header
	if !strings.Contains(contentStr, "Generated by camp") {
		t.Error(".envrc should have camp header")
	}
}

func TestSyncCmd_WithDevbox(t *testing.T) {
	// Create temporary directory
	tmpDir := t.TempDir()
	setupEnvrcTemplate(t, tmpDir)
	oldWd, _ := os.Getwd()
	os.Chdir(tmpDir)
	defer os.Chdir(oldWd)

	// Create .camp.yml
	campYaml := `env:
  TEST_VAR: "test-value"
`
	if err := os.WriteFile(".camp.yml", []byte(campYaml), 0644); err != nil {
		t.Fatalf("Failed to create .camp.yml: %v", err)
	}

	// Create devbox.json
	devboxJson := `{
  "packages": ["go"]
}`
	if err := os.WriteFile("devbox.json", []byte(devboxJson), 0644); err != nil {
		t.Fatalf("Failed to create devbox.json: %v", err)
	}

	// Run sync command
	err := syncProjectEnv()
	if err != nil {
		t.Fatalf("syncProjectEnv() failed: %v", err)
	}

	// Read and verify content
	content, err := os.ReadFile(".envrc")
	if err != nil {
		t.Fatalf("Failed to read .envrc: %v", err)
	}

	contentStr := string(content)

	// Should have devbox integration
	if !strings.Contains(contentStr, "devbox generate direnv") {
		t.Error(".envrc should include devbox integration when devbox.json exists")
	}

	// Should also have camp env vars
	if !strings.Contains(contentStr, "export TEST_VAR=\"test-value\"") {
		t.Error(".envrc should export TEST_VAR")
	}
}
